name: shellcheck test

on:
  push:
    branches: [ main ]

jobs:
  ubuntuLatestTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - name: Shellcheck VaST BASH scripts
        run: |
          for i in *sh; do
            shellcheck --severity=error $i
          done
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8 Python linter
        run: flake8 filter_report.py
