name: Ubuntu deploy test

on:
  push:
    branches: [ main ]

permissions:
  contents: read  # Minimal permissions to access repository content

jobs:
  ubuntuLatestTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - name: Shellcheck VaST BASH scripts
        run: |
          for i in *sh; do
            shellcheck --severity=error $i
          done
      - name: Install Flake8
        run: pip install flake8 && flake8 --version
      - name: Run Flake8 Python linter
        run: |
          for i in filter_report.py upload.py3; do
            flake8 --ignore=W293,W291,E501,E128,E722 $i
          done
      - name: Install VaST dependencies
        run: sudo apt-get install gfortran libx11-dev libpng-dev 
      - name: Install rarfile for Python
        run: |
          sudo apt-get install -y unrar
          pip install rarfile
          python3 -c "import rarfile" 2>/dev/null && echo "rarfile is available" || echo "rarfile is not available"
      - name: Run self-test script
        run: bash unmw_selftest.sh
        
